% This script loads and aggregates in a single file all the single
% simulation files generated by the cluster for the simulation made through
% the runner04 script.

clear all

Niter=100;
initial=1;
final=1;
maxval=1584;
sstep=1;

prop_coop_good=zeros(maxval,Niter);
prop_coop_good(:,:)=NaN;

touched_good=zeros(maxval,Niter); %useful only the first time.
touched_good(:,:)=NaN;

Simnamebase='MemoryVsAmountGossip_alternative';

while initial<=maxval
    disp(num2str(initial));
    
    for i=1:100
        disp(num2str(i));
        SimName=[Simnamebase '_' num2str(initial) '_' num2str(final) '_' num2str(i) '.mat']; %creo nome file

        load(SimName); %caricofile
            
        prop_coop_good(initial,i)=prop_coop(initial,i);
    end
    initial=initial+sstep;
    final=final+sstep;
    if final>maxval; final=maxval; end  
end

prop_coop=prop_coop_good;
clear prop_coop_good touched_good

save([Simnamebase 'new.mat']);
