% This script loads and aggregates in a single file all the single
% simulation files generated by the cluster for the simulation made through
% the runner03 script.


clear all

Niter=100;
initial=1;
final=1;
maxval=576;
sstep=1;

prop_coop_good=zeros(maxval,Niter);


Simnamebase='OutDatedInfoVsAmountGossip_alternative';

while initial<=maxval
    disp(num2str(initial));
    
    for count=1:100
        disp(num2str(count));
        SimName=[Simnamebase '_' num2str(initial) '_' num2str(final) '_' num2str(count) '.mat']; %create file name
        load(SimName); % Load the micro-file   
        prop_coop_good(initial,count)=prop_coop(initial,count);
    end
    initial=initial+sstep;
    final=final+sstep;
    if final>maxval; final=maxval; end  
end

clear prop_coop
prop_coop=prop_coop_good;
clear prop_coop_good touched_good


save([Simnamebase '.mat']);

