% This script loads and aggregates in a single file all the single
% simulation files generated by the cluster for the simulation made through
% the runner10 script.

clear all

Niter=100;

initial=1;
final=1;
maxval=5;
step=1;

prop_coop_good=zeros(3,5,Niter,1000);
prop_coop_good(:,:,:,:)=NaN;
touched_good=zeros(3,5,Niter,1000);
touched_good(:,:)=NaN;

Simnamebase='ContentOfGOssip_populationSize';

while initial<=maxval
    [initial final]
    
    SimName=[Simnamebase '_' num2str(initial) '_' num2str(final) '.mat']; %create name file
    if isfile(SimName)
        load(SimName); load file
    
        for j=1:maxval
            for i=1:3
                for iter=1:Niter
                    if touched(i,j,iter)==1
                        prop_coop_good(i,j,iter,:)=prop_coop(i,j,iter,:);
                        touched_good(i,j,iter)=touched(i,j,iter);
                    end
                end
            end
        end
    end
    
    initial=initial+step;
    final=final+step;
    if final>maxval; final=maxval; end
end

    
clear prop_coop touched
touched=touched_good;
prop_coop=prop_coop_good;
clear prop_coop_good touched_good


save([Simnamebase '.mat']);