% This script loads and aggregates in a single file all the single
% simulation files generated by the cluster for the simulation made through
% the runner06 script.

Niter=100;

initial=1;
final=1;
maxval=5;
step=1;

prop_coop_good=zeros(2,5,Niter);
prop_coop_good(:,:,:)=NaN;
touched_good=zeros(2,5,Niter);
touched_good(:,:)=NaN;

Simnamebase='ContentOfGOssip_theta';

while initial<=maxval
    [initial final]
    %ContentOfGossip_alternative
    SimName=[Simnamebase '_' num2str(initial) '_' num2str(final) '.mat']; %creo nome file
    if isfile(SimName)
        SimName
        load(SimName); %caricofile
    
        for j=1:maxval
            for i=1:3
                for iter=1:Niter
                    if touched(i,j,iter)==1
                        prop_coop_good(i,j,iter)=prop_coop(i,j,iter);
                        touched_good(i,j,iter)=touched(i,j,iter);
                    end
                end
            end
        end
    end
    
    initial=initial+step;
    final=final+step;
    if final>maxval; final=maxval; end
end

save([Simnamebase '.mat']);